---
# Install httpd on targer machines
- hosts: slavenodes
  tasks:
   - name: install apache web server 
     apt:
       pkg: apache2
       state: present
       update_cache: true

   - name: Push default virtual host configuration
     copy:
       src: files/vhost
       dest: /etc/apache2/sites-available/vhost
       mode: 0640

   - name: Activates our virtualhost
     command: a2ensite vhost 

   - name: Check that our config is valid
     command: apache2ctl configtest

   - name: Deactivates the default virtualhost
     command: a2dissite default

   - name: Deactivates the default ssl virtualhost
     command: a2dissite default-ssl
     notify:
       - restart apache
       #   - name: Disable the default virtualhost
       #     file:
       #       dest: /etc/apache2/sites-enabled/default
       #       state: absent
       #     notify:
       #       - restart apache
       #
       #   - name: Disable the default ssl virtualhost
       #     file:
       #       dest: /etc/apache2/sites-enabled/default-ssl
       #       state: absent
       #     notify:
       #       - restart apache
       #
       #   - name: Activates our virtualhost
       #     file:
       #       src: /etc/apache2/sites-available/vhost
       #       dest: /etc/apache2/sites-enabled/vhost
       #       state: link
       #     notify:
       #       - restart apache

  handlers:
   - name: restart apache
     service:
       name: apache2
       state: restarted
...
